engineer = input("Engineer Name: ")
project = input("Project Name: ")
file = open("review_note.txt", "w")
file.write("Safety Review Summary\n")
file.write("----------------------\n")
file.write("Engineer: " + engineer + "\n")
file.write("Project: " + project + "\n")
file.write("Status: Review Pending\n")
file.close()
print("Review note created successfully")
file = open("review_note.txt", "r")
content = file.read()
print(content)
file.close()